services:
  user:
    container_name: user
    ports:
      - "8000:8000"
    depends_on:
      - pg
    environment:
      PG_URL: "postgresql+asyncpg://ibragim:admin123321@pg:5432/UserDB"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      AUTH_SECRET_KEY: "09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7"
      STMT_KEY: "uele ehpj oedg edja"
      SMTP_EMAIL: "wendypython17@gmail.com"
      
    build: ./

  pg:
    container_name: pg
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ibragim
      POSTGRES_PASSWORD: admin123321
      POSTGRES_DB: UserDB

    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
     

  redis:
    container_name: redis
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always


volumes:
  redis_data:
  pgdata:
