"""Create User table

Revision ID: 75678a01ff9f
Revises:
Create Date: 2025-04-13 12:08:45.680081

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from datetime import datetime
import uuid

# revision identifiers, used by Alembic.
revision: str = "75678a01ff9f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "users",
        sa.Column("id", sa.Integer, index=True, primary_key=True),
        sa.Column("username", sa.String, nullable=False),
        sa.Column("email", sa.String, nullable=False),
        sa.Column("is_active", sa.Boolean, default=False),
        sa.Column("is_closed", sa.Boolean, default=False),
        sa.Column("picture_url", sa.String, nullable=True),
        sa.Column("created_at", sa.DateTime, default=datetime.utcnow()),
        sa.Column("token", sa.UUID, default=uuid.uuid4()),
        sa.Column("password", sa.String, nullable=False),
        sa.Column("name", sa.String, nullable=True),
    )
    pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
